### ISSUE TITLE
experiment on KITTI

### ISSUE THREAD

**Issue by illuosion** [MISTLab/Swarm-SLAM#11]
If I want to do an image experiment on a KITTI dataset, where should I download the standard dataset which is applied to Swarm-SLAM?could u give a link?

**Comment by illuosion** [comment]
and I have problem in graco， the graco_lidar.launch.py has been run 2h,is it possible?
<img width="962" alt="屏幕截图 2023-05-14 172357" src="https://github.com/MISTLab/Swarm-SLAM/assets/63509752/d373486e-d4d2-464d-95aa-d998e5d1d1da">

**Comment by lajoiepy** [comment]
Hi! Unfortunately, I don't have download links for those massive datasets. I rely on theirs authors for the dataset availability. So you will have to download, split and convert the KITTI dataset yourself : https://www.cvlibs.net/datasets/kitti/ , https://github.com/tomas789/kitti2bag , https://discourse.ros.org/t/rosbags-the-pure-python-library-for-everything-rosbag/20944

**Comment by lajoiepy** [comment]
For the second problem, one or more nodes must have crashed. Please check if all ros2 nodes are still alive with `ros2 node list`, you can post the output here.

**Comment by illuosion** [comment]
> For the second problem, one or more nodes must have crashed. Please check if all ros2 nodes are still alive with `ros2 node list`, you can post the output here.

<img width="425" alt="image" src="https://github.com/MISTLab/Swarm-SLAM/assets/63509752/600cb6af-5bf9-4824-ac9b-00e799b4ed4d">
 btw ，how 2 visualize the odometry result and map while testing graco

**Comment by illuosion** [comment]
> 

<img width="419" alt="image" src="https://github.com/MISTLab/Swarm-SLAM/assets/63509752/ce5f9cf1-0bf5-4ef6-be79-41273eeec044">

**Comment by illuosion** [comment]
> > 
> 
> <img alt="image" width="419" src="https://user-images.githubusercontent.com/63509752/238653997-ce5f9cf1-0bf5-4ef6-be79-41273eeec044.png">

the final output above

**Comment by illuosion** [comment]
> > > 
> > 
> > 
> > <img alt="image" width="419" src="https://user-images.githubusercontent.com/63509752/238653997-ce5f9cf1-0bf5-4ef6-be79-41273eeec044.png">
> 
> the final output above

<img width="1261" alt="屏幕截图 2023-05-16 211321" src="https://github.com/MISTLab/Swarm-SLAM/assets/63509752/e28dc214-d9d2-4a33-8ec6-37ca09e0192f">
should I change some params ?

**Comment by lajoiepy** [comment]
According to your screenshot one of the pose graph manager has crashed which explains the observed behavior. This is probably due to a out-of-memory error. Running multiple Swarm-SLAM agents + ROS 2 bags on a single computer requires a lot of RAM. I suggest that you reduce the rate at which the ROS 2 bags are played and the time offset between them https://github.com/lajoiepy/cslam_experiments/blob/9f72df6549478e55643e5c1ae566675d14faee13/launch/datasets_experiments/kitti_lidar.launch.py#L135 and https://github.com/lajoiepy/cslam_experiments/blob/9f72df6549478e55643e5c1ae566675d14faee13/launch/datasets_experiments/kitti_lidar.launch.py#L130
Alternatively, you can decrease the Swarm-SLAM performance by increasing the various loop periods available in the configuration files such as https://github.com/lajoiepy/cslam_experiments/blob/9f72df6549478e55643e5c1ae566675d14faee13/config/kitti_lidar.yaml#L15
The best solution is to run each agent on a different computer in the same network as this is the target design of Swarm-SLAM.

You can see the odometry results with `ros2 topic echo /rX/odom` where X is the robot ID.
Also you can visualize a live visualization of the pose graph estimates using https://github.com/lajoiepy/cslam_visualization

**Comment by illuosion** [comment]
My server has 32 GB RAM，how the system performs if I use 2 robots

**Comment by lajoiepy** [comment]
I want to clarify that the system does not shutdown on itself. It keeps running until you kill it. I strongly suggest that you run the [cslam_visualization](https://github.com/lajoiepy/cslam_visualization) to see the results. You can also enable logging https://github.com/lajoiepy/cslam_experiments/blob/9f72df6549478e55643e5c1ae566675d14faee13/config/kitti_lidar.yaml#L34 and see the resulting files in your log_folder.
