### ISSUE TITLE
Is your code not automatically exiting?

### ISSUE THREAD

**Issue by TwiceMao** [MISTLab/Swarm-SLAM#13]
Is your code not automatically exiting? 
Then how can I see the estimated pose of the output in the saved path of the estimated pose of the output?
Because I need to calculate the ATE metric with the pose estimated by Swarm-SLAM.

I successfully ran graco_lidar.launch.py. The two ros2 bags, ground_2 and ground_3, are used, because ground_1 is really difficult to download successfully.
It ran successfully for about tens of minutes, and the terminal has always been the following continuous output:
But I use cslam_visualization to visualize it, and I feel that the trajectory has finished running, so what should I do?

I successfully ran graco_lidar.launch.py. The two ros2 bags, ground_2 and ground_3, are used, because ground_1 cannot be downloaded .
It ran successfully for about tens of minutes, and the terminal has always been the following continuous output:
But I use cslam_visualization to visualize it, and I feel that the trajectory has finished running, so what should I do?

![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/fcdd43b6-a86a-4943-b8b6-825385361de5)

![image](https://github.com/MISTLab/Swarm-SLAM/assets/43490149/51aa1450-a74d-4295-be5e-d929986cae10)

**Comment by lajoiepy** [comment]
Indeed, the code never stops, you need to kill it yourself. If you enabled logging https://github.com/lajoiepy/cslam_experiments/blob/9f72df6549478e55643e5c1ae566675d14faee13/config/graco_lidar.yaml#L35 you should see results in your log_folder. Otherwise, you can create a small ros2 node that listen to the same pose graph messages as the visualization (see https://github.com/lajoiepy/cslam_visualization/blob/3240ca015e3b27036b3cecb7147c232a0fd456cd/cslam_visualization/pose_graph_visualizer.py#L18 ) and save them to a file.

**Comment by ResearcherYan** [comment]
@TwiceMao Hi TwiceMao, I've also successfully run the `graco_lidar.launch.py` with normal `/r0/odom` data published, as shown in [issue 31](https://github.com/MISTLab/Swarm-SLAM/issues/31#issuecomment-1996767118). But I can't visualize the pose like you did using [cslam_visualization](https://github.com/lajoiepy/cslam_visualization/tree/main). When I launch cslam_visualization, the rviz is always blank.

![cslam_visualization_rviz](https://github.com/MISTLab/Swarm-SLAM/assets/46956622/6e9b171f-7e6c-4ba7-8fda-855c3df1e05e)

Did you modify the settings of cslam_visualization to successfully show the poses? Could you help me? Thank you so much!
