### ISSUE TITLE
Request tutorials for open-sourced datasets (ex. EuRoC, KITTI)

### ISSUE THREAD

**Issue by minje-KIM** [MISTLab/Swarm-SLAM#2]
Hello, thank you for releasing a great research.

I finished building to implement your research on my computer, but I don't know how to run the algorithm with the open source dataset such as EuRoC.

I read your **Start-up Instructions**, and there was only a tutorial on real-robot. 
Can you give me a guide how to run open source datasets on your algorithm?

**Comment by lajoiepy** [comment]
Thanks for your interest!
The launch files for the datasets experiments are here: https://github.com/lajoiepy/cslam_experiments/tree/main/launch/datasets_experiments
 
The datasets are all available from third parties. For example, the GrAco dataset: [paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=10008011) , [ROS 1&2 bags](https://sites.google.com/view/graco-dataset/download) .

You only need to fix the path to the ROS 2 bags in the launch file, e.g.
https://github.com/lajoiepy/cslam_experiments/blob/d1c7d277786bc7a5df2898e55f088d0e16d53ee0/launch/datasets_experiments/graco_lidar.launch.py#L81
Then you can launch Swarm-SLAM!

Unfortunately, the EuRoC dataset is currently incompatible, since its stereo images are monochromes and the Visual Place Recognition networks we support (CosPlace and NetVLAD) require RGB images. Thus, to support this dataset, you will need to use another place recognition algorithm.

Soon, I'll add a more detailed dataset tutorial in the instructions.
