### ISSUE TITLE
Topics must be synchronized

### ISSUE THREAD

**Issue by mjforan** [MISTLab/Swarm-SLAM#37]
Another tip for the documentation:
For visual (RGBD/Stereo) SLAM, all input topics must be synchronized (image, camera_info, odometry).  If the timestamps are not approximately the same then the filter will drop messages and the frontend will do nothing. This can happen if nodes are running on different computers with a clock offset or if some topics are being replayed from a bag.

**Comment by lajoiepy** [comment]
Sorry for the delayed response. Thanks for pointing this out. 
This is expected behavior since the timestamps are used to associate the odometry messages with the corresponding sensor data frames (images, pointclouds, etc.).
I forgot to initially include this in the instructions, so I added a line on this.
