### ISSUE TITLE
Swarm-slam on two-turtlebot3 burger slam

### ISSUE THREAD

**Issue by faberpis** [MISTLab/Swarm-SLAM#46]
Hi! How can I adapt Swarm-SLAM to an a multi-robot slam with two turtlebot3 burger (simulations on gazebo, with ros2 humble)? I found a lot of problems.

**Comment by lajoiepy** [comment]
Hi! Thanks for your interest in Swarm-SLAM.

As far as I know, the turtlebot3 burger only has a 2D lidar sensor onboard.
This is problematic since Swarm-SLAM support only 3D lidar, RGB-D and stereo cameras. 
To make the stack work with 2D lidars you will need to code and integrate your own 2D lidar place recognition, and your own 2D lidar scan registration.
Look into this issue for some insights: https://github.com/lajoiepy/cslam_experiments/issues/8
